name: Local PlantUML run
description: Run plantuml using locally downloaded jar file
inputs:
  version:
    description: Plantuml version to use
    default: latest
    required: false
  cache-plantuml-jar:
    description: >
      Cache the downloaded plantuml.jar
    default: 'true'
    required: false
  cli-arguments:
    description: CLI arguments for plantuml
    default: '-h'
    required: false
  jvm-options:
    description: Options for the JVM
    default: ''
    required: false

outputs:
  plantuml-release-tag-used:
    description: Release tag of the PlantUML jar used in this invocation
    value: ${{ steps.plantuml-version.outputs.value }}
  is-cached-jar-file-used:
    description: true if previously cached jar file was used in this invocation
    value: ${{ steps.cached-plantuml.outputs.cache-hit }}

runs:
  using: composite

  steps:
    # To make this action OS-agnostic, we need to explicitly compute the install path
    # and shell for the following reasons:
    # 1. The Windows directory separator (backslash \) is treated as escape character
    #    in bash, which rules out(*) using bash in Windows runs.
    # 2. Composite actions does not support a default shell: https://github.com/actions/runner/blob/fb6d1adb430a6c96407c5857854a40662af439c8/docs/adrs/1144-composite-actions.md#defaults---not-being-considered-at-this-time
    #
    # (*) By enclosing the entire path in single quotes, the backslash can be preserved
    #     in bash, but this feels to me like an ugly and unintuitive workaround.
    - name: Compute OS-specific config
      id: os-specific-config
      shell: bash
      run: |
        if [ '${{ runner.os }}' != 'Windows' ]; then
          echo "install-path=${{ runner.temp }}/plantuml.jar" >> "$GITHUB_OUTPUT"
          echo "shell=bash" >> "$GITHUB_OUTPUT"
        else
          echo "install-path=${{ runner.temp }}\plantuml.jar" >> "$GITHUB_OUTPUT"
          echo "shell=pwsh" >> "$GITHUB_OUTPUT"
        fi

    - name: Compute PlantUML version to download
      id: plantuml-version
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        if [ '${{ inputs.version }}' = 'latest' ]; then
          LATEST_RELEASE_TAG=$(gh api repos/plantuml/plantuml/releases/latest \
          --jq .tag_name)
          echo "value=$LATEST_RELEASE_TAG" >> "$GITHUB_OUTPUT"
        else
          echo "value=v${{ inputs.version }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Load cached plantuml
      id: cached-plantuml
      if: ${{ inputs.cache-plantuml-jar == 'true' }}
      uses: actions/cache@v4.2.0
      with:
        path: ${{ steps.os-specific-config.outputs.install-path }}
        key: plantuml-jar-${{ runner.os }}-${{ steps.plantuml-version.outputs.value }}

    - name: Compute plantuml source path
      id: plantuml-source-path
      if: steps.cached-plantuml.outputs.cache-hit != 'true'
      shell: bash
      run: |
        PLANTUML_RELEASES_BASE_URL=https://github.com/plantuml/plantuml/releases/
        RELEASE_PATH=download/${{ steps.plantuml-version.outputs.value }}
        echo "value=$PLANTUML_RELEASES_BASE_URL/$RELEASE_PATH/plantuml.jar" \
          >> "$GITHUB_OUTPUT"

    - name: Install plantuml
      if: steps.cached-plantuml.outputs.cache-hit != 'true'
      shell: ${{ steps.os-specific-config.outputs.shell }}
      run: >
        curl -Ls
        -o "${{ steps.os-specific-config.outputs.install-path }}"
        ${{ steps.plantuml-source-path.outputs.value }}

    - name: Run plantuml
      shell: ${{ steps.os-specific-config.outputs.shell }}
      run: >
        java ${{ inputs.jvm-options }}
        -jar ${{ steps.os-specific-config.outputs.install-path }}
        ${{ inputs.cli-arguments }}
