name: run-plantuml-local
description: Run plantuml using locally downloaded jar file
inputs:
  version:
    description: Plantuml version to use
    default: latest
    required: false
  cache-plantuml-jar:
    description: >
      Cache the downloaded plantuml.jar
      [ignored if version is specified as 'latest']
    default: 'true'
    required: false
  cli-arguments:
    description: CLI arguments for plantuml
    default: '-h'
    required: false
  jvm-options:
    description: Options for the JVM
    default: ''
    required: false

runs:
  using: composite

  steps:
    # To make this action OS-agnostic, we need to explicitly compute the install path
    # and shell for the following reasons:
    # 1. The Windows directory separator (backslash \) is treated as escape character
    #    in bash, which rules out(*) using bash in Windows runs.
    # 2. Composite actions does not support a default shell: https://github.com/actions/runner/blob/fb6d1adb430a6c96407c5857854a40662af439c8/docs/adrs/1144-composite-actions.md#defaults---not-being-considered-at-this-time
    #
    # (*) By enclosing the entire path in single quotes, the backslash can be preserved
    #     in bash, but this feels to me like an ugly and unintuitive workaround.
    - name: Compute OS-specific config
      id: os-specific-config
      shell: bash
      run: |
        if [ '${{ runner.os }}' != 'Windows' ]; then
          echo "install-path=${{ runner.temp }}/plantuml.jar" >> "$GITHUB_OUTPUT"
          echo "shell=bash" >> "$GITHUB_OUTPUT"
        else
          echo "install-path=${{ runner.temp }}\plantuml.jar" >> "$GITHUB_OUTPUT"
          echo "shell=pwsh" >> "$GITHUB_OUTPUT"
        fi

    - name: Load cached plantuml
      id: cached-plantuml
      if: ${{ inputs.cache-plantuml-jar == 'true' && inputs.version != 'latest' }}
      uses: actions/cache@v4.0.2
      with:
        path: ${{ runner.temp }}/plantuml.jar
        key: plantuml-jar-${{ inputs.version }}

    - name: Download plantuml
      if: steps.cached-plantuml.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [ '${{ inputs.version }}' = 'latest' ]; then
          PLANTUML_DOWNLOAD_URL=https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
        else
          PLANTUML_DOWNLOAD_URL=https://github.com/plantuml/plantuml/releases/download/v${{ inputs.version }}/plantuml.jar
        fi
        curl -L -o ${{ runner.temp }}/plantuml.jar $PLANTUML_DOWNLOAD_URL

    - name: Run plantuml
      shell: bash
      run: |
        java ${{ inputs.jvm-options }} -jar ${{ runner.temp }}/plantuml.jar ${{ inputs.cli-arguments }}
