name: Test the action run-plantuml-local (dynamic edition)
on:
  workflow_run:
    workflows:
      - Generate Dynamic Test Workflow
    types:
      - completed

jobs:
  dynamic-override-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Describe Dynamic Override (success case)
        run: >
          echo "::info::"
          "This is a placeholder job. The dynamic workflow generated on the configured trigger "
          "events should override this with the actual job(s), which may naturally have "
          "different names."
          "\n"
          "\n"
          "We use this workaround because of the Github Actions UX defect that requires a workflow "
          "file on the main branch in order for the workflow to run from a side branch, "
          "pull request, etc."
          && exit 0

  dynamic-override-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: Describe Dynamic Override (failure case)
        run: >
          echo "::error::"
          "This is a placeholder job. It will run if the dynamic workflow generation fails. This "
          "ensures the overall workflow sequence is marked as a failure. For additional safety, "
          "we recommend that the dynamic workflow created includes a job that runs on failure of "
          "the dynamic workflow creation job. This covers the scenario where the dynamic workflow "
          "is created, but the creation job fails for some reason."
          "\n"
          "\n"
          "We use this workaround because of the Github Actions UX defect that requires a workflow "
          "file on the main branch in order for the workflow to run from a side branch, "
          "pull request, etc."
          && exit 1

  trigger-on-side-branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ secrets.PAT_ACTIONS }}
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Trigger on side branch
        run: |
          echo "::info::Triggering on side branch 'test-${{ github.event.workflow_run.head_sha }}'."
          gh workflow run dynamic-test.yml \
            --ref ${{ github.event.workflow_run.head_branch }} \
            --repo ${{ github.repository }} \
            --field "ref=test-${{ github.event.workflow_run.head_sha }}" \
            --field "trigger_sha=${{ github.event.workflow_run.head_sha }}"
          echo "::info::Triggered on side branch."
        env:
          GH_TOKEN: ${{ secrets.PAT_ACTIONS }}
